name: Mintify
# Note: Contributors can set DEVELOPMENT_TEAM in Xcode after generating project

options:
  bundleIdPrefix: com.yourname
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    PRODUCT_NAME: Mintify
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  Mintify:
    type: application
    platform: macOS
    sources:
      - path: Mintify
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourname.Mintify
        INFOPLIST_FILE: Mintify/Info.plist
        CODE_SIGN_ENTITLEMENTS: Mintify/Mintify.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        MARKETING_VERSION: "2.0"
        CURRENT_PROJECT_VERSION: "2"
